services:
  #postgres container
  db:
    image: postgres:15
    container_name: postgres-soap
    environment:
      POSTGRES_DB: soap_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  #mongo container
  mongodb:
    image: mongo:latest
    container_name: dogs_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    volumes:
      - dogs_data:/data/db
    networks:
      - my_network

  #redis container
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  #soap-api container
  api-soap:
    build:
      context: ./SoapApi
      dockerfile: Dockerfile
    hostname: soap-api
    container_name: soap-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=soap_api
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
    networks:
      - my_network

  #rest-flask-api container
  flask-app:
    build:
      context: ./RestApi
      dockerfile: Dockerfile
    image: emmanuel/dog_api_1.0.0
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./RestApi:/app
    depends_on:
      - mongodb
      - redis
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    networks:
      - my_network

volumes:
  dogs_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
  