apiVersion: v1
kind: Secret
metadata:
  name: soapapi-secrets
  namespace: ema-api
type: Opaque
data:
  connection-string: cG9zdGdyZXNxbDovL2FkbWluOm15cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvZG9nc19kYg== # Checar este asunto...

