apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\diego\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rest-api
  name: rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\diego\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: rest-api
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
            - name: REDIS_URL
              value: redis://redis:6379/0
          image: emmanuel/dog_api_1.0.0
          name: rest-api
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: flask-app
      restartPolicy: Always
      volumes:
        - configMap:
            name: flask-app
          name: flask-app
--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\diego\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rest-api
  name: rest-api
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: rest-api
