apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: ema-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: emmanuel/dog_api_1.0.0:latest
        env: 
        - name: "MONGO_URI"
          valueFrom:
            secretKeyRef:
              name: restapi-secrets
              key: connection-string
        ports:
        - containerPort: 5000
