apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: flask-app
  name: flask-app
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30001 
  selector:
    io.kompose.service: flask-app
